Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Style/NumericPredicate:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
